// Angular/projects/deepseek-gui/src/app/components/thinking-progress/thinking-progress.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-thinking-progress',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div *ngIf="active" class="thinking-overlay">
      <img src="assets/ai_thinking.gif" alt="Thinking..." class="thinking-svg" />
    </div>
  `,
  styleUrls: ['./thinking-progress.component.scss']
})
export class ThinkingProgressComponent {
  @Input() active: boolean = false;
}

// csharp/IFOllama.React/src/components/ThinkingProgress.tsx
import './ThinkingProgress.scss';

interface ThinkingProgressProps {
  active: boolean;
}

export function ThinkingProgress({ active }: ThinkingProgressProps) {
  if (!active) return null;

  return (
    <div className="thinking-overlay">
      <div className="thinking-panel">
        <img src={`${import.meta.env.BASE_URL}ai_thinking.gif`} alt="Thinking..." className="thinking-gif" />
        <span>Thinking...</span>
      </div>
    </div>
  );
}
